apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: populated-pvc
spec:
    dataSourceRef:
        name: example-name
        kind: ExampleDataSource
        apiGroup: example.storage.k8s.io
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
            