---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
    name: new-snapshot-test
spec:
    volumeSnapshotClassName: csi-hostpath-snapclass
    source:
        persistentVolumeClaimName: pvc-test
   
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
    name: test-snapshot
spec:
    source:
        volumeSnapshotContentName: test-content