apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
    name: new-snapshot-content-test
    annotations:
        - snapshot.storage.kubernetes.io/allow-volume-mode-change: "true"
spec:
    deletionPolicy: Delete
    driver: hostpath.csi.k8s.io
    source:
        snapshotHandle: 7bdd0de3-aaeb-11e8-9aae-0242ac110002
    sourceVolumeMode: Filesystem
    volumeSnapshotRef:
        name: new-snapshot-test
        namespace: default