apiVersion: v1
kind: Pod
metadata:
    name: my-pod
spec:
    containers:
        - name: my-container
          image: myimage
          resources:
              requests:
                  cpu: 2
                  example.com/foo: 1
              limits:
                  example.com/foo: 1
                  