apiVersion: v1
kind: ResourceQuota
metadata:
    name: disable-cross-namespace-affinity
    namespace: foo-ns
spec:
    hard:
        pods: "0"
    scopeSelector:
        matchExpressions:
            - scopeName: CrossNamespacePodAffinity
              operator: Exists
              