---
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration

profiles:
    - schedulerName: default-scheduler
      pluginConfig:
          - name: PodTopologySpread
            args:
                defaultConstraints:
                    - maxSkew: 1
                      topologyKey: topology.kubernetes.io/zone
                      whenUnsatisfiable: ScheduleAnyway
                defaultingType: List
                
---
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration

profiles:
    - schedulerName: default-scheduler
      pluginConfig:
          - name: PodTopologySpread
            args:
                defaultConstraints:
                    -   maxSkew: 3
                        topologyKey: "kubernetes.io/hostname"
                        whenUnsatisfiable: ScheduleAnyway
                    -   maxSkew: 5
                        topologyKey: "topology.kubernetes.io/zone"
                        whenUnsatisfiable: ScheduleAnyway
                defaultingType: List
                
---
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration

profiles:
    - schedulerName: default-scheduler
      pluginConfig:
          - name: PodTopologySpread
            args:
                defaultConstraints: []
                defaultingType: List