---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClass
name: resource.example.com
driverName: resource-driver.example.com
---
apiVersion: cats.resource.example.com/v1
kind: ClaimParameters
name: large-black-cat-claim-parameters
spec:
    color: black
    size: large
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
    name: large-black-cat-claim-template
spec:
    spec:
        resourceClassName: resource.example.com
        parametersRef:
            apiGroup: cats.resource.example.com
            kind: ClaimParameters
            name: large-black-cat-claim-parameters

–--
apiVersion: v1
kind: Pod
metadata:
    name: pod-with-cats
spec:
    containers:
        - name: container0
          image: ubuntu:20.04
          command: ["sleep", "9999"]
          resources:
              claims:
                  - name: cat-0
        - name: container1
          image: ubuntu:20.04
          command: ["sleep", "9999"]
          resources:
              claims:
                  - name: cat-1
    resourceClaims:
        - name: cat-0
          source:
              resourceClaimTemplateName: large-black-cat-claim-template
        - name: cat-1
          source:
              resourceClaimTemplateName: large-black-cat-claim-template
              