apiVersion: v1
kind: Pod
metadata:
    name: env-configmap
spec:
    containers:
        - name: envars-test-container
          image: nginx
          env:
              - name: CONFIGMAP_USERNAME
                valueFrom:
                    configMapKeyRef:
                        name: myconfigmap
                        key: username